# Generated by Django 6.0.7 on 2026-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'Not Started'), ('1', 'In Progress'), ('2', 'Done')], db_column='cs_status', default='0', max_length=1),
        ),
    ]
