# Generated by Django 6.0.7 on 2026-09-11 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_worked_hours',
            field=models.IntegerField(db_column='nb_total_worked_hours', default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_column='tx_title', max_length=100, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='TaskWorkTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField(db_column='nb_hours')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='dt_date')),
                ('task', models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.DO_NOTHING, to='core.task')),
            ],
            options={
                'db_table': 'task_work_time',
                'managed': True,
            },
        ),
    ]
